version: "3.8"

volumes:
  prometheus_data:

networks:
  website_monitoring:

services:
  prometheus:
    image: prom/prometheus:v2.43.0
    hostname: prometheus
    restart: always
    networks:
      - website_monitoring
    ports:
      - "127.0.0.1:9090:9090"
    user: nobody
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./config/prometheus/targets.yml:/etc/prometheus/targets.yml:ro"
      - "./config/prometheus/rules:/etc/prometheus/rules"
      - "prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.23.0
    hostname: blackbox
    restart: always
    networks:
      - website_monitoring
    volumes:
      - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  grafana:
    image: grafana/grafana:9.4.7
    hostname: grafana
    restart: always
    networks:
      - website_monitoring
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=CHANGEME"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes:
      - "./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
